# Generated by Django 4.1.2 on 2022-10-13 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_transaction_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('timestamp',)},
        ),
    ]
